<?php

namespace dLdL\ChatbotPlatform;

use dLdL\ChatbotPlatform\Event\RequestEvent;
use dLdL\ChatbotPlatform\Event\ReplyEvent;

/**
 * A message handler is notified when an HTTP request is received. It must choose
 * whether it can handle or not the request.
 *
 * A message handler may also be notified if a reply has been generated for any
 * parsed message. In this situation, it may generate a HTTP response and may
 * perform additional actions.
 */
interface MessageHandlerInterface
{
    /**
     * This method is called when a HTTP request is received, and no previous
     * handler has found a way to handle it.
     *
     * @param RequestEvent $event The request event containing the HTTP request
     */
    public function onRequest(RequestEvent $event): void;

    /**
     * This method is called when a message reply has been generated by any
     * message action. The message handler should generate an HTTP response if
     * it can handle the message type.
     *
     * @param ReplyEvent $event The reply event containing the generated reply
     */
    public function onReply(ReplyEvent $event): void;
}
